spring:
  application:
    name: "SSL"

  profiles:
    include: jwt, ai, file, security, admin, redis

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/bank
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate: info
